# Generated by Django 4.1.7 on 2023-03-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('isbn', models.IntegerField()),
                ('auther', models.CharField(max_length=20)),
                ('contents', models.CharField(max_length=300)),
                ('book_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
